name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    # Step 1: Checkout code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use Node.js 16 (or your desired version)

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run tests (optional, if you have any)
    - name: Run tests
      run: npm test

    # Step 5: Deploy to EC2
    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # SSH Key stored in GitHub secrets
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/github-action
        chmod 600 ~/.ssh/github-action
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-action ubuntu@13.57.249.156 << 'EOF'
          cd /home/ubuntu/nodejs
          git pull origin main  # Pull the latest code from GitHub
          npm install  # Install dependencies
          pm2 restart nodeapp  # Restart the Node.js app with PM2
        EOF
